import type { Provider, AISummary } from '@/types';

export const providers: Provider[] = [
  {
    id: 'p1',
    name: 'Dr. Sharma Pet Clinic',
    type: 'Vet',
    rating: 4.8,
    reviews: 342,
    verified: true,
    verifiedDaysAgo: 3,
    distanceKm: 2.1,
    openNow: true,
    hours: '9:00 AM – 8:00 PM',
    area: 'Saket, South Delhi',
    address: 'B-12, Press Enclave Road, Saket, New Delhi – 110017',
    phone: '+91 98100 12345',
    services: ['General Consultation', 'Vaccination', 'Surgery', 'Diagnostics', 'Dental Care'],
    animals: ['Dog', 'Cat', 'Rabbit', 'Bird'],
    emergency: true,
    isEmergencyPriority: true,
    yearsActive: 12,
    about:
      'A multi-speciality companion animal clinic led by Dr. Rajesh Sharma, BVSc & AH, with over 12 years of experience in small animal medicine and surgery. Equipped with in-house diagnostics, digital X-ray, and a dedicated surgical suite.',
  },
  {
    id: 'p2',
    name: 'Friendicoes SECA Rescue & Shelter',
    type: 'NGO / Rescue',
    rating: 4.7,
    reviews: 518,
    verified: true,
    verifiedDaysAgo: 7,
    distanceKm: 5.3,
    openNow: true,
    hours: '24 × 7',
    area: 'Okhla, South Delhi',
    address: 'Near Okhla Gaon, New Delhi – 110020',
    phone: '+91 98110 67890',
    services: ['Rescue Operations', 'Adoption', 'Shelter', 'Sterilisation', 'Emergency First Aid'],
    animals: ['All Animals'],
    emergency: true,
    yearsActive: 28,
    about:
      'One of Delhi’s oldest animal welfare NGOs, Friendicoes SECA has been rescuing and sheltering abandoned and injured animals since 1996. Runs a 24×7 helpline for injured street animals and operates mass sterilisation drives across the NCR.',
  },
  {
    id: 'p3',
    name: 'Paws & Claws Veterinary Hospital',
    type: 'Vet',
    rating: 4.6,
    reviews: 287,
    verified: true,
    verifiedDaysAgo: 5,
    distanceKm: 3.4,
    openNow: true,
    hours: '8:30 AM – 9:00 PM',
    area: 'Greater Kailash II',
    address: 'M-Block Market, GK-II, New Delhi – 110048',
    phone: '+91 98200 34567',
    services: ['General Consultation', 'Vaccination', 'Orthopaedic Surgery', 'Ultrasound', 'Pet Pharmacy'],
    animals: ['Dog', 'Cat', 'Bird'],
    emergency: false,
    yearsActive: 8,
    about:
      'Paws & Claws is a modern veterinary hospital offering advanced diagnostics, orthopaedic surgery, and routine wellness care. Known for a calm, pet-friendly environment and transparent pricing.',
  },
  {
    id: 'p4',
    name: 'Delhi Animal Ambulance Service',
    type: 'Ambulance',
    rating: 4.5,
    reviews: 156,
    verified: true,
    verifiedDaysAgo: 2,
    distanceKm: 4.8,
    openNow: true,
    hours: '24 × 7',
    area: 'Connaught Place',
    address: 'Block A, Connaught Place, New Delhi – 110001',
    phone: '+91 98300 88888',
    services: ['Emergency Transport', 'On-site First Aid', 'Rescue Pickup', 'Cremation Service'],
    animals: ['All Animals'],
    emergency: true,
    yearsActive: 6,
    about:
      'A 24×7 animal ambulance service covering all of Delhi NCR. Equipped with oxygen support, stretchers, and first-aid kits. Specialises in rapid pickup of injured street animals and emergency transport for pets.',
  },
  {
    id: 'p5',
    name: 'SafePaws Boarding & Daycare',
    type: 'Boarding',
    rating: 4.4,
    reviews: 198,
    verified: true,
    verifiedDaysAgo: 12,
    distanceKm: 6.7,
    openNow: true,
    hours: '8:00 AM – 7:00 PM',
    area: 'Vasant Kunj',
    address: 'C-8, Vasant Kunj, New Delhi – 110070',
    phone: '+91 98400 56789',
    services: ['Day Boarding', 'Overnight Stay', 'Grooming', 'Exercise Sessions'],
    animals: ['Dog', 'Cat'],
    emergency: false,
    yearsActive: 5,
    about:
      'SafePaws offers clean, spacious boarding and daycare for dogs and cats with supervised play areas, daily exercise, and optional grooming. All pets must be vaccinated before check-in.',
  },
  {
    id: 'p6',
    name: 'Sanjay Gandhi Animal Care Centre',
    type: 'NGO / Rescue',
    rating: 4.3,
    reviews: 621,
    verified: true,
    verifiedDaysAgo: 9,
    distanceKm: 8.2,
    openNow: true,
    hours: '24 × 7',
    area: 'Raja Garden',
    address: 'Shivaji Marg, Raja Garden, New Delhi – 110015',
    phone: '+91 98500 22222',
    services: ['Shelter', 'Sterilisation', 'Adoption', 'Free OPD', 'Rescue'],
    animals: ['All Animals'],
    emergency: true,
    yearsActive: 35,
    about:
      'Delhi’s largest animal shelter, caring for over 3,000 animals including dogs, cats, cows, and birds. Offers free OPD consultations, mass sterilisation, and an on-site pathology lab.',
  },
  {
    id: 'p7',
    name: 'Vets For Pets 24×7 Emergency',
    type: 'Vet',
    rating: 4.7,
    reviews: 412,
    verified: true,
    verifiedDaysAgo: 1,
    distanceKm: 5.9,
    openNow: true,
    hours: '24 × 7',
    area: 'Dwarka Sector 7',
    address: 'Plot 14, Sector 7, Dwarka, New Delhi – 110077',
    phone: '+91 98600 44444',
    services: ['Emergency Care', 'ICU', 'Surgery', 'Diagnostics', 'Vaccination'],
    animals: ['Dog', 'Cat', 'Rabbit'],
    emergency: true,
    isEmergencyPriority: true,
    yearsActive: 10,
    about:
      'A round-the-clock emergency and critical care hospital with a dedicated ICU, in-house blood bank, and 24×7 veterinary support. Equipped to handle trauma, poisoning, and post-operative recovery.',
  },
  {
    id: 'p8',
    name: 'Cure & Care Animal Hospital',
    type: 'Vet',
    rating: 4.2,
    reviews: 134,
    verified: false,
    verifiedDaysAgo: 45,
    distanceKm: 7.1,
    openNow: false,
    hours: '10:00 AM – 6:00 PM',
    area: 'Lajpat Nagar',
    address: 'F-Block, Lajpat Nagar II, New Delhi – 110024',
    phone: '+91 98700 99999',
    services: ['General Consultation', 'Vaccination', 'Minor Surgery'],
    animals: ['Dog', 'Cat'],
    emergency: false,
    yearsActive: 3,
    about:
      'A neighbourhood clinic offering affordable routine care, vaccinations, and minor surgical procedures. Verification is currently pending — please confirm details before visiting.',
  },
];

export const aiSummary: AISummary = {
  animalName: 'Bruno',
  species: 'Dog',
  breed: 'Labrador Retriever, 4 years',
  reportType: 'Complete Blood Count (CBC) + Biochemistry Panel',
  dateOfReport: '12 September 2026',
  keyFindings: [
    'Haemoglobin levels are slightly below the normal range (11.2 g/dL vs. normal 12–18 g/dL), suggesting mild anaemia.',
    'White blood cell count is within normal limits — no current indication of active systemic infection.',
    'ALT (liver enzyme) is mildly elevated (95 U/L vs. normal 10–85 U/L), which may warrant monitoring.',
    'Blood urea and creatinine are within normal ranges, indicating healthy kidney function.',
    'Platelet count is normal — no signs of clotting disorders.',
  ],
  medications: [
    { name: 'Sympocat (Antibiotic)', dosage: '250 mg, twice daily', duration: '7 days' },
    { name: 'Liv.52 (Liver Support)', dosage: '1 tablet, once daily', duration: '30 days' },
    { name: 'Iron Tonic (Haemup)', dosage: '5 ml, once daily', duration: '15 days' },
  ],
  followUp: 'Re-test CBC and liver enzymes after 3 weeks. Schedule a follow-up consultation with your veterinarian to assess improvement.',
  questionsToAsk: [
    'Could the mildly low haemoglobin be related to diet, or should we test for underlying causes like tick-borne disease?',
    'Is the slightly elevated ALT a concern, and should we do an ultrasound to check liver health?',
    'Are there any dietary changes you recommend while Bruno is on the iron tonic and liver support?',
    'Should we restrict exercise or activity during the antibiotic course?',
    'When exactly should we schedule the re-test — before or after finishing the current medication?',
  ],
};
